package com.notevault.notevault.entity;

import jakarta.persistence.*;

// Marks this class as a database table
@Entity
@Table(name="notes")
public class Note {

    // Primary Id: a unique identifier
    // Auto-increment value generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Title of the note
    private String title;

    // Actual content of the note
    private String content;

    // Default constructor: JPA required this
    public Note() {

    }

    // Constructor for creating objects manually
    public Note(String title, String content){
        this.title = title;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}
